### ISSUE TITLE
funny duplicate module error message 

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc#127] opened 2018-04-27 00:38 UTC
when i made a mistake in module definition (of a module here `BC`) and
used
`X: d$X`
instead of
`X: $X`

it gave me a funny error:
```
ERROR: [deploy_2]: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
script_3678249080779651339 in <module>
----> build_config_db(str(_input[0]), str(_output[0]), str(_output[1]), vanilla = vanilla, jobs = 2)

ValueError: 
Identical modules found: BC:f1f6636a!
```

**Comment by gaow** [comment] 2018-04-27 14:14
Still not able to reproduce but should be fixed in `master`. Please reopen if there is a future instance.

**Closed by gaow** 2018-04-27 14:14 UTC
