### ISSUE TITLE
[dscrutils] querying issue 

### ISSUE THREAD

**Issue by fmorgante** [stephenslab/dsc#184] opened 2019-04-24 16:16 UTC
I have had a problem querying the results of the attached example. 
[dsc_pred.tar.gz](https://github.com/stephenslab/dsc/files/3113244/dsc_pred.tar.gz)

When I use the following command, I get an empty object.
```r
> dsc <- dscquery("demo", c("score_mse.err", "score_r.err", "score_r2.err", "score_bias.err"), verbose=F)
> dsc
[1] DSC            score_mse.err  score_r.err    score_r2.err   score_bias.err
<0 rows> (or 0-length row.names)
```
However, when I also include the 'groups' argument, it returns the object as expected.

```r
> dsc <- dscquery("demo", c("score.err"),return.type='list', groups="score: score_mse score_r score_r2 score_bias", verbose=F)
> dsc
$DSC
[1] 1 1 1 1

$score
[1] "score_mse"  "score_r"    "score_r2"   "score_bias"

$score.err
$score.err[[1]]
[1] 0.6306824 2.4431124 6.9762797

$score.err[[2]]
[1] 0.5087264 0.3417742 0.3009097

$score.err[[3]]
[1] 0.25880257 0.11680964 0.09054668

$score.err[[4]]
yhat[, i] yhat[, i] yhat[, i] 
1.3090479 0.9626688 0.8930594 
``` 

According to @gaow this is a bug.

**Comment by gaow** [comment] 2019-04-24 16:22
Testing the `dsc-query` command on its own, the resulting temporary CSV file looks like:

```
 DSC                            score_mse.err.output
1   1 score_mse/sim_data_1_mnm_fit_pred_1_score_mse_1
2   1                                            <NA>
3   1                                            <NA>
4   1                                            <NA>
                           score_r.err.output
1                                        <NA>
2 score_r/sim_data_1_mnm_fit_pred_1_score_r_1
3                                        <NA>
4                                        <NA>
                            score_r2.err.output
1                                          <NA>
2                                          <NA>
3 score_r2/sim_data_1_mnm_fit_pred_1_score_r2_1
4                                          <NA>
                              score_bias.err.output
1                                              <NA>
2                                              <NA>
3                                              <NA>
4 score_bias/sim_data_1_mnm_fit_pred_1_score_bias_1
```

which is expected. I guess it is again issues handling `NA` when loading the results?

**Comment by pcarbo** [comment] 2019-04-24 21:47
@fmorgante @gaow This is not a bug; this is expected behavior. Read the description of the `targets` argument:

> targets: Query targets specified as a character vector… These are *required* targets; that is,
> DSC pipelines (i.e., rows of the returned data frame) in which one of more of the targets are 
> unassigned or missing (‘NA’) will be automatically removed. To allow for unassigned or missing 
> values, use argument ‘targets.notreq’ instead.

**Comment by gaow** [comment] 2019-04-24 22:23
Well, but you can see how our decision is confusing in this seemingly innocent request. That is why I initially thought it reasonable to only remove a line where all required targets are missing. I guess if it confuses me then it might be confusing to a broader audience.

**Comment by pcarbo** [comment] 2019-04-25 15:13
@fmorgante Since you have defined `score` already in your `.dsc` file, you can simply do

```R
out <- dscquery("demo","score.err")
```

Does that achieve what you were looking for?

Please reach out to Gao or I for guidance on designing and implementing the DSC and querying the results. The general intent of DSC is that if the DSC is well-designed, the `dscquery` calls should be fairly simple; on the other hand, if you are getting strange results, it is most likely because your DSC could be improved.

**Comment by gaow** [comment] 2019-04-25 15:26
@zouyuxin would you mind sharing the examples you discussed off-line with me here, including the temporary CSV file and the result data frame of the query (you can save to RDS and upload). @pcarbo Yuxin is also confused by the NA behavior even after she reads the documentation.

**Comment by fmorgante** [comment] 2019-04-25 15:47
@pcarbo Yes, that code works as I want. Thanks!

**Comment by zouyuxin** [comment] 2019-04-25 17:42
This is a query example I used in this DSC: https://github.com/stephenslab/dsc-finemap/blob/dsc-R/r_compare.dsc

The outputs below are in [test.zip](https://github.com/stephenslab/dsc/files/3118118/test.zip).

Using the `dsc-query` command,
```
dsc-query r_compare_add_z -o test.csv --target "get_sumstats sim_gaussian.pve susie.maxL susie_bhat.L susie_bhat_add_z.L susie_rss.L susie_rss_add_z.L finemap.ld_method finemap_add_z.ld_method score_susie.converged" --force
```
the test.csv file has 16201 rows.

In R,
```
dscout = dscquery('r_compare_add_z', targets = 'get_sumstats sim_gaussian.pve susie.maxL susie_bhat.L susie_bhat_add_z.L susie_rss.L susie_rss_add_z.L finemap.ld_method finemap_add_z.ld_method score_susie.converged', omit.filenames=F)
```
The output data frame contains 16200 rows and it contains NAs. For example,
```
> sum(is.na(dscout$get_sumstats.output.file))
[1] 1200
```
I want these NAs in the output, but it doesn't agree with the documentation, right? 
> DSC pipelines (i.e., rows of the returned data frame) in which one of more of the targets are
unassigned or missing (‘NA’) will be automatically removed

According to the documentation, these rows with NA should be removed? Is there anything I misunderstood?

**Comment by gaow** [comment] 2019-04-29 18:05
@pcarbo I think this issue should be resolved in here #182 , after we deprecate `target.notreq` and reports everything, should be resolved? Although it remains curious that @zouyuxin has find the current behavior does not remove `NA` even if it supposed to do it. I hope it is not some bugs in the code ...

**Comment by pcarbo** [comment] 2019-04-29 21:08
@zouyuxin I can't run your example without the DSC results. Do you have them stored somewhere on the RCC cluster?

**Comment by zouyuxin** [comment] 2019-04-29 21:13
They're stored in `/project/mstephens/SuSiE/susie_z/output/r_compare_add_z`

**Comment by pcarbo** [comment] 2019-04-29 21:44
@zouyuxin I got a data frame with zero rows:

```R
library(dscrutils)
out <- dscquery("r_compare_add_z",
                targets = c("get_sumstats","sim_gaussian.pve",
                            "susie.maxL","susie_bhat.L",
                            "susie_bhat_add_z.L","susie_rss.L",
                            "susie_rss_add_z.L","finemap.ld_method",
                            "finemap_add_z.ld_method",
                       	    "score_susie.converged"))
nrow(out)
# 0
```

This is my sessionInfo:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)
Matrix products: default
BLAS/LAPACK: /software/openblas-0.2.19-el7-x86_64/lib/libopenblas_haswellp-r0.2.19.so
locale:
[1] C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] dscrutils_0.3.8
loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0
```

**Comment by zouyuxin** [comment] 2019-04-29 22:13
@pcarbo I see. So 
```
dscquery("r_compare_add_z",
                targets = c("get_sumstats", "sim_gaussian.pve", ...))
```
is different form 
```
dscquery("r_compare_add_z",
                targets = "get_sumstats sim_gaussian.pve ..."))
```
I was using the later one, which gives me 16200 rows.

**Comment by gaow** [comment] 2019-04-29 23:54
@pcarbo guess this is where the bug is :P

**Comment by pcarbo** [comment] 2019-04-30 00:40
Not a bug:

```
 targets: Query targets specified as a character vector; for example,
          ‘targets = c("simulate.n","analyze","score.error")’.
```

**Comment by gaow** [comment] 2019-04-30 00:55
@pcarbo I believe my original interface takes both a vector and a string separated by space? We should fix it, and change the documentation to clearly indicate that we allow for the string format because it saves lots of typing when dozens of targets are asked for.

**Comment by pcarbo** [comment] 2019-04-30 16:25
@gaow I understand that is the original interface implemented in `dsc-query`, but it doesn't really doesn't make sense to do that in R.

**Comment by gaow** [comment] 2019-04-30 16:53
@pcarbo sure. Since it is a convention used a lot by myself and at least 2 other users I've allowed for it in the query interface. I'm cool with not using them in any of our examples in documentation (even though I'm not really convinced that it does not make sense to do in R).

**Closed by gaow** 2019-04-30 16:53 UTC
